package com.pos.pos_transaction.item_list.object;
// Generated Mar 25, 2015 11:50:11 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * MSubCategory generated by hbm2java
 */
public class MSubCategory  implements java.io.Serializable {


     private String hash;
     private MMainCategory MMainCategory;
     private String code;
     private String branch;
     private String name;
     private boolean active;
     private Set<MItem> MItems = new HashSet<MItem>(0);

    public MSubCategory() {
    }

	
    public MSubCategory(String hash, MMainCategory MMainCategory, String code, String branch, String name, boolean active) {
        this.hash = hash;
        this.MMainCategory = MMainCategory;
        this.code = code;
        this.branch = branch;
        this.name = name;
        this.active = active;
    }
    public MSubCategory(String hash, MMainCategory MMainCategory, String code, String branch, String name, boolean active, Set<MItem> MItems) {
       this.hash = hash;
       this.MMainCategory = MMainCategory;
       this.code = code;
       this.branch = branch;
       this.name = name;
       this.active = active;
       this.MItems = MItems;
    }
   
    public String getHash() {
        return this.hash;
    }
    
    public void setHash(String hash) {
        this.hash = hash;
    }
    public MMainCategory getMMainCategory() {
        return this.MMainCategory;
    }
    
    public void setMMainCategory(MMainCategory MMainCategory) {
        this.MMainCategory = MMainCategory;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Set<MItem> getMItems() {
        return this.MItems;
    }
    
    public void setMItems(Set<MItem> MItems) {
        this.MItems = MItems;
    }

@Override
    public int hashCode() {
        int hash = 3;
        hash = 97 * hash + Objects.hashCode(this.hash);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final MSubCategory other = (MSubCategory) obj;
        if (!Objects.equals(this.hash, other.hash)) {
            return false;
        }
        return true;
    }


}


